apiVersion: v1
kind: Pod
metadata:
  name: violating-pod
  labels:
    purpose: violate-policy
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    # Missing resources limits and requests
    test:test
    test1:test1
